server:
  port: 8080
  servlet:
    context-path: /cyk
spring:
  application:
    name: RedisTest
  cache:
    type: redis
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: 123456
    timeout: 10000ms
    jedis:
      pool:
        # 连接池最大连接数（负值表示无限制）
        max-active: 30
        # 连接池最大阻塞等待时间（负值无限制)
        max-wait: 5000ms
        # 最大空闲链接数
        max-idle: 8
        # 最小空闲链接数
        min-idle: 0